Update to fix error on input where feed metadata unavailable.
Example stack trace:

2015-11-02 17:32:14,156 - WARNING - Could not open feed metadata: data/feeds/4.json
Traceback (most recent call last):
  File "/usr/bin/cb-event-duplicator", line 9, in <module>
    load_entry_point('cb-event-duplicator==1.1.1', 'console_scripts', 'cb-event-duplicator')()
  File "/usr/lib/python2.6/site-packages/cb_event_duplicator-1.1.1-py2.6.egg/cbopensource/tools/eventduplicator/data_migration.py", line 132, in main
    t.transport(debug=options.verbose)
  File "/usr/lib/python2.6/site-packages/cb_event_duplicator-1.1.1-py2.6.egg/cbopensource/tools/eventduplicator/transporter.py", line 267, in transport
    self.output_feed_doc(doc)
  File "/usr/lib/python2.6/site-packages/cb_event_duplicator-1.1.1-py2.6.egg/cbopensource/tools/eventduplicator/transporter.py", line 45, in output_feed_doc
    self.output.output_feed_metadata(feed_metadata)
  File "/usr/lib/python2.6/site-packages/cb_event_duplicator-1.1.1-py2.6.egg/cbopensource/tools/eventduplicator/solr_endpoint.py", line 361, in output_feed_metadata
    original_id = doc_content['id']
TypeError: 'NoneType' object is unsubscriptable